# fly.toml file generated for solar-app on 2023-03-01T05:03:52-05:00

app = "solar-app"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "3003"
  SECRET = "testSecret"
  MONGODB_URL = "mongodb+srv://admin:rlkQ1HOjBUWjNwol@cluster0.rtsqfn0.mongodb.net/solarApp?retryWrites=true&w=majority"
  TEST_MONGODB_URL = "mongodb+srv://admin:rlkQ1HOjBUWjNwol@cluster0.rtsqfn0.mongodb.net/testSolarApp?retryWrites=true&w=majority"


[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 3003
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
